### PR TITLE
Use tap-runner for mutation testing

### PR DESCRIPTION
**Pull request by nicojs**
Enable stryker ava using the tap runner

### CODE REVIEW

**Comment by ericcornelissen** [comment]
Thanks for the Pull Request @nicojs, I updated it to avoid the error you mentioned [here](https://github.com/stryker-mutator/stryker-js/issues/3245#issuecomment-1605392576) and to use the runner in both Stryker configurations.

I want to do some more testing with `--incremental` mode before I merge this, potentially removing [the conditional use of incremental mode in CI](https://github.com/ericcornelissen/shescape/blob/24bd2f471c663876f0677b77dde8d750483b5317/.github/workflows/checks.yml#L436-L441).

One thing I noticed in [the logs](https://github.com/ericcornelissen/shescape/actions/runs/5363970352/jobs/9732587166?pr=991#step:10:19) was that it shows `NaN%`:

```log
Mutation testing NaN% (elapsed: <1m, remaining: n/a) 17/399 tested (0 survived, 0 timed out)
Mutation testing NaN% (elapsed: <1m, remaining: n/a) 32/399 tested (0 survived, 0 timed out)
...
```

Haven't looked at it yet, I don't know if it's due to the new version, new test runner, or something else - but figured you'd want to know.

**Comment by nicojs** [comment]
I've noticed that as well. Will do some more digging later. Thanks

**Comment by nicojs** [comment]
Why is the pipeline failing?

**Comment by nicojs** [comment]
See https://github.com/stryker-mutator/stryker-js/issues/4331 regarding progress reporting

**Comment by ericcornelissen** [comment]
> Why is the pipeline failing?

- `Check / Mutation (integration)`: this was an oversight on my part. The integration tests require a [transpiled](https://github.com/ericcornelissen/shescape/blob/6c9df26edfa17820106c371de4ca80aa7cda2e9f/package.json#L116) version of the library, which was previously there because the `mutation:integration` ran `npm run test:integration` but with the switch to `tap-runner` no longer held. I updated this in d596bd0f83571ebd3697775006320004cbbd1cb8 and should no longer fail.
- `Check / Semgrep`: this is failing due to a permission error because it requires a secret that's not accessible from forks (:unamused:). Can be ignored for now and I'll be looking into a solution (probably run the check only on `main`?).
- `Check / Audit / npm`: this can be ignored, it's due to a recently published CVE in the [`semver` package](https://www.npmjs.com/package/semver) and also fails on the `main branch (see also #992).

**Pull request merged**
